@Backend_HostAddress = http://localhost:5170
@pollkey = mobil2000
POST {{Backend_HostAddress}}/questions
Content-Type: application/json

{
    "QuestionKey" : "q2",
    "Text" : "Do you think this product looks cool?",
    "PollKey" : "{{pollkey}}"
}
###

GET {{Backend_HostAddress}}/questions?pollKey={{pollkey}}
Content-Type: application/json

###
POST {{Backend_HostAddress}}/Polls?pollkey={{pollkey}}
Content-Type: application/json

###
GET {{Backend_HostAddress}}/Polls
Content-Type: application/json

### post json with answers
POST {{Backend_HostAddress}}/Answers
Content-Type: application/json

{
    "User" : "Adamasky",
    "PollKey" : "{{pollkey}}",
    "Answers" : [1,2,3,4],
    "QKeys" : ["Q1","Q2","Q3","Q4"]
}

### get all answers
GET {{Backend_HostAddress}}/Answers?pollkey={{pollkey}}
Content-Type: application/json

### post all questions from client
POST {{Backend_HostAddress}}/Questions
Content-Type: application/json

{"data":[["q1","gillar du grönt?"],["q2","gillar du rött?"]],"key":"fnuffenull"}