@Backend_HostAddress = http://localhost:5170

GET {{Backend_HostAddress}}/weatherforecast/
Accept: application/json
###
@pollkey = nya_mobilappen
GET {{Backend_HostAddress}}/questions?pollKey={{pollkey}}
Content-Type: application/json

###
