@Backend_HostAddress = http://localhost:5170
@pollkey = nya_mobilappen
POST {{Backend_HostAddress}}/questions
Content-Type: application/json

{
    "QuestionKey" : "q2",
    "Text" : "Do you recommend this to your worst enemy?",
    "PollKey" : "nya_mobilappen"
}
###

GET {{Backend_HostAddress}}/questions?pollKey={{pollkey}}
Content-Type: application/json

###
